# Generated by Django 5.2.9 on 2025-12-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_device_id_attendancerecord_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='annotated_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
