# Generated by Django 5.2.9 on 2025-12-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_annotated_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='annotated_image_path',
        ),
    ]
