# Generated by Django 5.2.9 on 2025-12-31 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendancerecord_annotated_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='present_in_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='present_in_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_captures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('pending', 'Pending Verification')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CaptureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_number', models.IntegerField()),
                ('image_path', models.CharField(max_length=500)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('faces_detected', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['session', 'capture_number'],
                'unique_together': {('session', 'capture_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_w', models.IntegerField(blank=True, null=True)),
                ('bbox_h', models.IntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_detections', to='attendance.capturerecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_appearances', to='attendance.student')),
            ],
            options={
                'ordering': ['capture__capture_number'],
                'unique_together': {('capture', 'student')},
            },
        ),
    ]
